# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f2cee2688a588019c31cb05d864e257aaabe3a3790af96e4d82c09083715bb46d3fd3eab400041ee2140e4095a0c0133447b6d76dd09ceb96d13d2e249ffb4e

test:
  secret_key_base: 35af07da49d7228115edc014b89864d0e168ce750ff391094e8d4defde47f32ad2e1a2f44b4242c6956a7e727fa8ff94da543c3d1b01a0acb9cd68e28cb1fd14

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
